### ISSUE TITLE
get temperature

### ISSUE THREAD

**Issue by hAckyD** [Erriez/ErriezMHZ19B#1]
Hi there,

it would be really awesome if you could implement sensor temperature readout, so it would be possible to get the current sensor temperature too.

Please see the following link as an example: https://www.blikk.it/forum/blog.php?bn=neuemedien_fb&lang=de&id=1575901160 

Apparently, the temperature in degrees Celsius + 40 (to account for possible negative temperature numbers) is being transmitted in byte 5, so you only have to substract 40. Because `return` can only return a single value, the code from the page mentioned above uses variables and pointers:
```
void readSensor(int *ppm, int *temperature){
  byte cmd[9] = {0xFF,0x01,0x86,0x00,0x00,0x00,0x00,0x00,0x79};
  byte response[9]; 
  co2Serial.write(cmd, 9);
  memset(response, 0, 9);
  while (co2Serial.available() == 0) {
    delay(1000);
  }
  co2Serial.readBytes(response, 9);
  (...)
  *ppm = 256 * (int)response[2] + response[3];
  *temperature = response[4] - 40;
}
```

Thank you!
hAcky

**Comment by Erriez** [comment]
Hi hAckyD,

Thanks for using my library and feature request! I've added reading the temperature as you requested in a new  branch `add-temperature`:

https://github.com/Erriez/ErriezMHZ19B/tree/feature/add-temperature

The getting started example demonstrates the usage of the new function `uint8_t getTemperature()`. Serial output example:

```
846 ppm, 18 C
845 ppm, 18 C
...
```

For this library, I tried to use only documented commands. Reading the temperature is not documented, but it seems to work. All reverse-engineered commands: https://revspace.nl/MHZ19

Can you test this with your sensor and let me know if it works? Then I'll update the documentation and merge this in master.

Thanks!
Erriez

**Comment by hAckyD** [comment]
Hi Erriez,

thank you and sorry for the late answer.

It works fine for me!

hAcky

**Comment by Erriez** [comment]
@hAckyD, Thanks for getting back to me. I've tested the temperature sensor on different devices for more than a week and noticed a big deviation with other accurate temperature sensors. I'll check if this temperature read functionality can be optimized away when not used to prevent wasting flash/RAM.

**Comment by Erriez** [comment]
Decided to keep MH-Z19B temperature in branch [add-temperature](https://github.com/Erriez/ErriezMHZ19B/tree/feature/add-temperature) as it is undocumented and contains a high temperature deviation.
Closing issue.
