### ISSUE TITLE
Analog Voltage Output

### ISSUE THREAD

**Issue by FadhilLuthfi** [Erriez/ErriezMHZ19B#10]
### Feature request

Read analog voltage output using pin Vo

### Hardware setup

ESP32, Arduino Uno

### Is your feature request related to a problem?

I have a project to ensure the output voltage from pin Vo is similar to the output PPM using the UART pin. But I don't have any reliable code to compare these two output.these two outputs

### Describe the solution you'd like

In the library, could help me to add the reading of the voltage output from the Vo pin?

### Checks

- [X] I understand that this library is maintained by volunteers in spare time. Response time may vary.

### Export restrictions.

- [X] I accept [End User Agreement](https://github.com/Erriez/ErriezMHZ19B/blob/master/END_USER_AGREEMENT.md).

**Comment by Erriez** [comment]
@FadhilLuthfi Thanks for using my library. It supports reading the CO2 value only via a software or hardware serial port as is much more stable compared with Vo. For this reason I've no plans to support Vo and recommend to use the UART or another sketch.

**Comment by FadhilLuthfi** [comment]
Hello what about the temperature, is sensor capable to read temperature?

**Comment by Erriez** [comment]
> Hello what about the temperature, is sensor capable to read temperature?

Both MH-Z19B and MH-Z19C contain a built-in temperature sensor which is used for CO2 compensation calculation. Reading the temperature registers is possible, but not documented and the accuracy of this temperature is very low (not useful, not useful for applications). For this reason, I decided in https://github.com/Erriez/ErriezMHZ19B/issues/1 not supporting the temperature sensor in master, but there is a branch https://github.com/Erriez/ErriezMHZ19B/tree/feature/add-temperature which supports reading temperature for MH-Z19B with function `readTemperature()`.

**Comment by FadhilLuthfi** [comment]
Hello. Thank fo the answer. I want to ask again, I already installed your
lib about temperature but I figure it out that the code for readtemperature
is not working. Could you help me with to find the solution?
Thank you

[image: 742834f6-b187-4e04-8f1a-8cd2b22deefe.png]

**Comment by Erriez** [comment]
The [add-temperature](https://github.com/Erriez/ErriezMHZ19B/tree/feature/add-temperature) branch was tested for MH-Z19B only. I'm not able to help as both official [MH-Z19B datasheet](https://github.com/Erriez/ErriezMHZ19B/blob/master/extras/mh-z19b-co2-ver1_0.pdf) and [MH-Z19C datasheet](https://github.com/Erriez/ErriezMHZ19B/blob/master/extras/mh-z19c-co2-ver1_21.pdf) does not describe how to read the temperature. So you try to implement a feature which is not officially supported by the manufacture.

**Comment by FadhilLuthfi** [comment]
Mine is MHZ19B. But why the code is not work?

**Comment by FadhilLuthfi** [comment]
Hello, Could you help me with this question? I am researching the
characteristics of CO2 through MHZ19B for my thesis. Do you know what kind
of electricity characteristics that affected by CO2 concentration change?

Noted:
Electricity Characteristics: Could be voltage, current, capacitance or etc

**Comment by Erriez** [comment]
Sorry, I cannot help answering your questions. Success with your thesis.
