### ISSUE TITLE
Why is the value only 400ppm? 

### ISSUE THREAD

**Issue by thanapol199717** [Erriez/ErriezMHZ19B#2]
Hello, I need help
I'm not sure why Co2 is only 400 ppm, but I've tried mouth-watering. 
The value has changed, I'm not sure if my sensor is normal.
![image](https://user-images.githubusercontent.com/74811728/122072406-ba504f00-ce21-11eb-8d13-216119f1b1b9.png)

Thanks in advance for the answer

**Comment by thanapol199717** [comment]
Sorry, last time I sent it to DHT 22.

**Comment by Erriez** [comment]
@thanapol199717 Did you try to power the MH-Z19B sensor continuous for more than 5 minutes? It takes some time before the sensor generates valid data and is normal behavior. You can try to blow into the sensor a couple of times which should increase the value. Is that what you mean with `mouth-watering`?

Another suggestion is to check the calibration mode. Automatic baseline calibration is executed every 24 hours and requires around 15-30 minutes in fresh air once a day or week for good calibration results.
 
Note: 400 ppm is the minimum CO2 value of outdoor air.

**Comment by thanapol199717** [comment]
Thank you very much for you answer me.​ 
oh, it means blow.​ I blow it and it changed.
Is my sensor normal?

**Comment by Erriez** [comment]
> oh, it means blow.​ I blow it and it changed.

No problem :-)

> Is my sensor normal?

It takes time before the value changes (around 30..60 seconds minute) and that's normal. I suggest to put the sensor in a room with doors/windows closed and measure/log the CO2 values when at least one person is inside the room. Test the sensor with >24 hours powered. After a couple of hours, the CO2 value increases. A value of 400ppm is outdoor clean air, above 800ppm indicates that the room needs ventilation, above 1200 is unhealthy and above 2000 is dangerous. Success!
