### ISSUE TITLE
How you implement Smart warming up function ?

### ISSUE THREAD

**Issue by MIKHANYA** [Erriez/ErriezMHZ19B#3]
How you implement Smart warming up function ?

**Comment by Erriez** [comment]
It is located here:

https://github.com/Erriez/ErriezMHZ19B/blob/8a163d57d587b53571ba1f2a1083de460a505afd/src/ErriezMHZ19B.cpp#L96

A combination of minimum time after power-on and exit warming-up on a CO2 value change.

**Comment by MIKHANYA** [comment]
Trying to write it on my own, but there is something with data. And I must reset Processor to get true data, actually don't understand how to avoid it

**Comment by Erriez** [comment]
Did you run the example https://github.com/Erriez/ErriezMHZ19B/tree/master/examples/ErriezMHZ19BGettingStarted ?

**Comment by MIKHANYA** [comment]
Yes, I use your example, with uncommented  "MHZ19B_SMART_WARMING_UP" it works fine
