### ISSUE TITLE
new sensor MH-Z19C 

### ISSUE THREAD

**Issue by Sorki11** [Erriez/ErriezMHZ19B#4]
Do you also have a Library Version for the MH-Z19C Sensor?

**Comment by Erriez** [comment]
Thanks for your question. The main difference between MH-Z19B and MH-Z19C is related to CO2 accuracy/performance and as far as I can see the registers are identical. I do not own a MH-Z19C so I cannot test it, but it looks like compatible. Can you give it a try?

**Comment by Erriez** [comment]
This library is compatible with MH-Z19B and MH-Z19C as the API is identical.
