### ISSUE TITLE
MH-Z19C also works on firebeetle 

### ISSUE THREAD

**Issue by hanscees** [Erriez/ErriezMHZ19B#7]
### Board

dfrobot firebeetle esp32-e v1.0

### Hardware setup

I have gotten it working using 
```

#include <HardwareSerial.h>
HardwareSerial mhzSerial( 2 );
#define MHZ19B_TX_PIN        16
#define MHZ19B_RX_PIN        17

// Create MHZ19B object
ErriezMHZ19B mhz19b(&mhzSerial);
```

The firebeetle has 3 uart devices, but the first uses the same pins as the usb power port, the second is more complex to operate, so the third one is the simplest to use. 

see 
https://microcontrollerslab.com/esp32-uart-communication-pins-example/

### Version

latest master (checkout manually)

### IDE Name

arduino 

### Description

this is not a bug but a comment. Thank you for making this library, the libraries with pwm here and there I couldnt get to work.
I am using the winsen mh-z19C 

If anything could be improved, you write that calibrating by hardware is undocumented.
For the mh-z19c is this not so, see

 https://www.tinytronics.nl/shop/index.php?route=product/product/get_file&file=3109/MH-Z19C-DZ-terminal%20type%20CO2%20Manual(Ver1.21)-202103.pdf

Also the pins for the 19C are different. 

In the section zero-calibration the hand-operated method is documented. Short out pin 1 for more than 7 second. 
I have done so and that works fine.

### Testcase

there's no problem, sorry

### Sketch

```cpp
no
```

### Logs

```plain
n0
```

### Checks

- [X] I understand that this library is maintained by volunteers in spare time. Response time may vary.

### Export restrictions.

- [X] I accept [End User Agreement](https://github.com/Erriez/ErriezMHZ19B/blob/master/END_USER_AGREEMENT.md).

**Comment by Erriez** [comment]
@hanscees Thanks for your feedback. I'm glad to hear that your MH-Z19C works after changing the pins. I've updated this in https://github.com/Erriez/ErriezMHZ19B/pull/8. Do you think this is clear and sufficient?

Note: I do not own the MH-Z19C, but the datasheet is helpful.

Nogmaals bedankt een een fijne dag! (Thanks again and have a nice day)

**Comment by hanscees** [comment]
It looks clear to me, but hard to read when not published for me
