### ISSUE TITLE
MH-Z19C not working with Wemos D1 Mini

### ISSUE THREAD

**Issue by T0biasCZe** [Erriez/ErriezMHZ19B#9]
### Board

Wemos D1 mini

### Hardware setup

Wemos D1 Mini (clone) and MH-Z19C.

### Version

latest master (checkout manually)

### IDE Name

Arduino Ide

### Description

When trying to use RX TX pins other than the default D6 D5, the code throws "Detecting MH-Z19B sensor..." even though the sensor is correctly connected to the set pins.

### Testcase

1) upload the board bellow and connect the green/blue wire to D6/D5.  the library will correctly find the sensor.
2) change the TX and RX pin, for example to D1/D2
3) connect the wires to the different pins
4) upload the code. the code will keep printing "Detecting MH-Z19B sensor..."

### Sketch

```cpp
#include <ErriezMHZ19B.h>
#define MHZ19B_TX_PIN D5
#define MHZ19B_RX_PIN D6

#include <SoftwareSerial.h>  // Use software serial
SoftwareSerial mhzSerial(MHZ19B_TX_PIN, MHZ19B_RX_PIN);

// Create MHZ19B object
ErriezMHZ19B mhz19b(&mhzSerial);
void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  mhzSerial.begin(9600);
    while (!mhz19b.detect()) {
    Serial.println(F("Detecting MH-Z19B sensor..."));
    delay(1000);
  };
  Serial.println("found");
}

void loop() {}
```

### Logs

```plain
N/A
```

### Checks

- [X] I understand that this library is maintained by volunteers in spare time. Response time may vary.

### Export restrictions.

- [X] I accept [End User Agreement](https://github.com/Erriez/ErriezMHZ19B/blob/master/END_USER_AGREEMENT.md).

**Comment by Erriez** [comment]
@T0biasCZe Thanks for using my library. A communication problem with the MH-Z19C is likely when the message `Detecting MH-Z19B sensor...` is printed in a loop. Can you check if the MH-Z19C is powered with a stable 5V? The device works properly above 4.5V. The IO pins are 3.3V compatible. The 5V pin voltage of the Wemos D1 is sometimes too low. You can try to power the MH-Z19C with an external 5V power supply or connect a capacitor (around 220uF) over the 5V.

Please notice that the MH-Z19B and MH-Z19C pins are different. This is is updated recently in the README.md:
https://github.com/Erriez/ErriezMHZ19B#pins
I assume D5 and D6 can be used for TX/RX software serial interface. Can you check if this is correctly wired?
